### ISSUE TITLE
Create user's dog routes

### ISSUE THREAD

**Issue by lind1125** [SFX818/Team-2-backend#4]
- [x] GET	`'/Profile/dogs/:dogid'` (View data on one of your dogs)
- [x] PUT	`'/Profile/dogs/:dogid'` (Update one of your dog's profiles)
- [x] DELETE	`'/Profile/dogs/:dogid'` (Delete one of your dog's profile)
- [x] POST `'/Profile/dogs/:dogid'` (Create one of your dog's profile)

**Comment by monicaleep** [comment]
Starting on this but will probably not finish today, i will push the branch and update this comment.

**Comment by monicaleep** [comment]
Ok what I've done so far is on the 'dog-routes' branch which is also on github. Pending are the put and delete routes, and of course cloudinary
