### ISSUE TITLE
Create fetched dog routes

### ISSUE THREAD

**Issue by lind1125** [SFX818/Team-2-backend#6]
- [ ] GET `'/profile/dogs/:dogid/dogs'` (View other dogs served from database based on preferences)
- [ ] PUT	'/profile/dogs/:dogid/add'	 Add a dog you like / reject depending on req.body?
- [ ] GET	`/profile/dogs/:dogid/matches'`	View your dog's matches

**Comment by monicaleep** [comment]
I think this should be split out to 3 separate ones to easier assign tasks and split work?

**Comment by monicaleep** [comment]
#12 #11 #10 created to close this one
